### ISSUE TITLE
Userstyle wrecks codebox newlines

### ISSUE THREAD

**Issue by LogicalJoe** [Legend-of-iPhoenix/cemetech-userstyle#49] opened 2021-09-06 06:01 UTC
Check out the awesome code at the bottom of this post.
https://ceme.tech/p293027
Without userstyle
<img width="879" alt="Screen Shot 2021-09-06 at 01 56 54" src="https://user-images.githubusercontent.com/47825483/132167619-00ed321c-c5e0-465e-902e-cde651032a94.png">
With userstyle
<img width="850" alt="Screen Shot 2021-09-06 at 01 57 35" src="https://user-images.githubusercontent.com/47825483/132167668-85bdf98b-6971-4e7e-aae1-821d5e315637.png">(It also copies this code)

**Comment by Legend-of-iPhoenix** [comment] 2021-09-06 13:25
This is a duplicate of #45

**Closed as completed by Legend-of-iPhoenix** 2021-09-06 13:25 UTC
Labels: duplicate
